
allowed_paths:
  - "README.md"
  - "students/**"


error_message: |
  ❌ PR содержит изменения в запрещённых файлах или директориях.
  Разрешены изменения только в:
  - README.md
  - Директории students/ и её содержимом

  fdjkghfjkghc